### ISSUE TITLE
delete this？

### ISSUE THREAD

**Issue by cerebrowang** [CPdogson/996action#113]
delete this

**Comment by cerebrowang** [comment]
我从CMCC 4G 网络过来

**Comment by mika-cn** [comment]
這邊也是：
404

There isn't a GitHub Pages site here.

**Comment by chinyichun** [comment]
不要紧，https://996.icu 和 https://www.996.icu 都不是996.ICU本尊，而是周边网站。只要GitHub上的996.ICU本尊没事儿就行了，其它的周边网站就不要去管它们了。
