### ISSUE TITLE
关于网易裁员事件

### ISSUE THREAD

**Issue by wangxingkang** [CPdogson/996action#122]
# 相关链接 

* [网易裁员，让保安把身患绝症的我赶出公司。我在网易亲身经历的噩梦！](https://mp.weixin.qq.com/s/FW7uR5t6UMMxgkCcAvk-MA)
* [网易出来道歉了](https://mp.weixin.qq.com/s/iW7VbZUHxqk6uRDzZfje1w)

**Comment by wangxingkang** [comment]
希望发起个活动 卸载网易应用，本人已全部卸载，贡献下自己小小的力量

**Comment by VincentWallace8012** [comment]
打蛇要打七寸，你卸载的网易应用，只不过是人家本来就不赚钱的产品，有啥意义呢？

建议看看 这个报道
https://finance.sina.com.cn/chanjing/gsnews/2019-11-25/doc-iihnzhfz1626162.shtml
中国经济周刊，对于网易来说，他的各大应用已经收费乏力
唯独游戏应用是盈利的
网易游戏应用分为 PC和手机2类。还有他的网易UU加速器。

而网易游戏推广平台，除了他自己的网易游戏平台
还有B站，谷歌，苹果商店，taptap和steam
国内的这些平台，例如B站和TAPTAP。
大家可以在评论区里宣传这位游戏策划的事迹，让大家不要玩带血的游戏，同时发动大家给游戏超低分。
而国外的平台，网易的游戏是要给老外玩的。所以
建议大家把游戏策划的事情，翻译成英文，发到reddit等国外贴吧上。把问题扩散。可以利用谷歌翻译等工具。
紧接着，steam是可以负面评分同时发布玩家评论的，直接转载英文版本评论给英文玩家，因为他的游戏都是免费机制，完全可以下载以后给差评
而谷歌商店和苹果商店也是一样的模式，大家可以贴负面评价，宣传网易劣迹，然后给1星。
让外国玩家不要支持黑心中国企业做的游戏。

而他的UU加速器，我们可以通过推广比他更便宜的雷神腾讯等加速器。
绝对可以抢到机会，因为本来他UU就做的很差。

直接影响网易唯一盈利的游戏产业。

**Comment by VincentWallace8012** [comment]
对国外宣传的时候，大家可以把马特达蒙的电影极乐空间截取片段来做配合宣传
极乐空间里，达蒙被强迫关在车间里遭受辐射得了绝症然后被无情解雇
咱们可以把网易宣传成现实版的极乐空间公司。

**Comment by darkPress** [comment]
这个时代，资本基本完成了对市场的统治，市场在谁手里，我们便要为谁服务，从流程上简单的看，资本实际上只是供给和需求的中间桥梁。我们所被动的是，要必须通过这个桥梁才能完成自己的需求和供给交换的过程，那么有没有一个方法可以绕过这座并不那么友好，有时候甚至有些恐怖的桥梁呢？
其实这就是为什么信息技术行业的很多人都憧憬去中心化网络的一个本质原因。当你清楚的意识到，资本不可相信，政府不可迷信，你就会自然的诞生这样的想法。我们的路在我们自己的脚下，只有当我们越来越团结我们才可以眺望更远，只有当我们团结起来的人越来越多我们脚下的路才会越来越宽广。
是一刻都放不下生活的重担，变得只能选择屈从在资本的鞭子下苟且的活着，还是肯花点时间思考这些问题，肯花点经历找到一条大家团结交流促进的路，究竟怎么选择？

**Comment by VulperVoid** [comment]
> 打蛇要打七寸，你卸载的网易应用，只不过是人家本来就不赚钱的产品，有啥意义呢？
> 
> 建议看看 这个报道
> https://finance.sina.com.cn/chanjing/gsnews/2019-11-25/doc-iihnzhfz1626162.shtml
> 中国经济周刊，对于网易来说，他的各大应用已经收费乏力
> 唯独游戏应用是盈利的
> 网易游戏应用分为 PC和手机2类。还有他的网易UU加速器。
> 
> 而网易游戏推广平台，除了他自己的网易游戏平台
> 还有B站，谷歌，苹果商店，taptap和steam
> 国内的这些平台，例如B站和TAPTAP。
> 大家可以在评论区里宣传这位游戏策划的事迹，让大家不要玩带血的游戏，同时发动大家给游戏超低分。
> 而国外的平台，网易的游戏是要给老外玩的。所以
> 建议大家把游戏策划的事情，翻译成英文，发到reddit等国外贴吧上。把问题扩散。可以利用谷歌翻译等工具。
> 紧接着，steam是可以负面评分同时发布玩家评论的，直接转载英文版本评论给英文玩家，因为他的游戏都是免费机制，完全可以下载以后给差评
> 而谷歌商店和苹果商店也是一样的模式，大家可以贴负面评价，宣传网易劣迹，然后给1星。
> 让外国玩家不要支持黑心中国企业做的游戏。
> 
> 而他的UU加速器，我们可以通过推广比他更便宜的雷神腾讯等加速器。
> 绝对可以抢到机会，因为本来他UU就做的很差。
> 
> 直接影响网易唯一盈利的游戏产业。

本以为996icu已经RIP了，之前各种行动最终都没取得什么成果。
不过今天来看到了这个issue，要不要趁着网易这次的事件再集体行动一下？

**Comment by wangxingkang** [comment]
不管对网易影响有多大  做点什么 总比不做强

**Comment by VincentWallace8012** [comment]
> > 打蛇要打七寸，你卸载的网易应用，只不过是人家本来就不赚钱的产品，有啥意义呢？
> > 建议看看 这个报道
> > https://finance.sina.com.cn/chanjing/gsnews/2019-11-25/doc-iihnzhfz1626162.shtml
> > 中国经济周刊，对于网易来说，他的各大应用已经收费乏力
> > 唯独游戏应用是盈利的
> > 网易游戏应用分为 PC和手机2类。还有他的网易UU加速器。
> > 而网易游戏推广平台，除了他自己的网易游戏平台
> > 还有B站，谷歌，苹果商店，taptap和steam
> > 国内的这些平台，例如B站和TAPTAP。
> > 大家可以在评论区里宣传这位游戏策划的事迹，让大家不要玩带血的游戏，同时发动大家给游戏超低分。
> > 而国外的平台，网易的游戏是要给老外玩的。所以
> > 建议大家把游戏策划的事情，翻译成英文，发到reddit等国外贴吧上。把问题扩散。可以利用谷歌翻译等工具。
> > 紧接着，steam是可以负面评分同时发布玩家评论的，直接转载英文版本评论给英文玩家，因为他的游戏都是免费机制，完全可以下载以后给差评
> > 而谷歌商店和苹果商店也是一样的模式，大家可以贴负面评价，宣传网易劣迹，然后给1星。
> > 让外国玩家不要支持黑心中国企业做的游戏。
> > 而他的UU加速器，我们可以通过推广比他更便宜的雷神腾讯等加速器。
> > 绝对可以抢到机会，因为本来他UU就做的很差。
> > 直接影响网易唯一盈利的游戏产业。
> 
> 本以为996icu已经RIP了，之前各种行动最终都没取得什么成果。
> 不过今天来看到了这个issue，要不要趁着网易这次的事件再集体行动一下？

那么现在请从第一步开始，谁的英语好，把当事人朋友圈的信息翻译成英语，
翻译砸了估计老外懒得看啊

**Comment by VincentWallace8012** [comment]
> 不管对网易影响有多大 做点什么 总比不做强

我简单的观察了一下

呼吁删除网易应用的评论
----------这个只会引来冷嘲热讽，甚至还有人问，网易有啥应用值得你用啊
事实说明，网易的应用实际上，能够引起大家关注的，其实比较少
不管是网易公开课，还是有道，都是很容易被替代的。你发起抵制，可能大家本来就不用，影响不大

而有些试图给网易游戏打差评，甚至在B站给网易的周边作品例如阴阳师
甚至网易暴雪合作项目进行公开抵制的评论，反而会引出很多反感的人，甚至还有为网易游戏说好话的
-------个人认为
网易游戏才是网易的利益所在，也是切实能够影响到网易忠实用户，甚至网易根本的。因此才会导致有人针对和刺激性反应
因此，个人建议，从多个方面
一方面是steam平台
另一方面，看看能否对暴雪发出海外公开信，拒绝与吃人血馒头的网易合作
因为网易暴雪的游戏合作项目，恰恰刚好就是这位患病游戏策划的服务项目之一

我们不要期待彻底封杀网易的游戏业务，只要能动摇或者影响。让其不得不在这个问题上服软
对绝症游戏策划做出赔偿和公开道歉的姿态，这就是基本目的达成了

顺带一提，根据媒体公布的，这位绝症策划的劳动仲裁时间为12月10日 杭州劳仲委

**Comment by VincentWallace8012** [comment]
> > 打蛇要打七寸，你卸载的网易应用，只不过是人家本来就不赚钱的产品，有啥意义呢？
> > 建议看看 这个报道
> > https://finance.sina.com.cn/chanjing/gsnews/2019-11-25/doc-iihnzhfz1626162.shtml
> > 中国经济周刊，对于网易来说，他的各大应用已经收费乏力
> > 唯独游戏应用是盈利的
> > 网易游戏应用分为 PC和手机2类。还有他的网易UU加速器。
> > 而网易游戏推广平台，除了他自己的网易游戏平台
> > 还有B站，谷歌，苹果商店，taptap和steam
> > 国内的这些平台，例如B站和TAPTAP。
> > 大家可以在评论区里宣传这位游戏策划的事迹，让大家不要玩带血的游戏，同时发动大家给游戏超低分。
> > 而国外的平台，网易的游戏是要给老外玩的。所以
> > 建议大家把游戏策划的事情，翻译成英文，发到reddit等国外贴吧上。把问题扩散。可以利用谷歌翻译等工具。
> > 紧接着，steam是可以负面评分同时发布玩家评论的，直接转载英文版本评论给英文玩家，因为他的游戏都是免费机制，完全可以下载以后给差评
> > 而谷歌商店和苹果商店也是一样的模式，大家可以贴负面评价，宣传网易劣迹，然后给1星。
> > 让外国玩家不要支持黑心中国企业做的游戏。
> > 而他的UU加速器，我们可以通过推广比他更便宜的雷神腾讯等加速器。
> > 绝对可以抢到机会，因为本来他UU就做的很差。
> > 直接影响网易唯一盈利的游戏产业。
> 
> 本以为996icu已经RIP了，之前各种行动最终都没取得什么成果。
> 不过今天来看到了这个issue，要不要趁着网易这次的事件再集体行动一下？

网易和被裁的已经和解了
https://tech.sina.com.cn/i/2019-11-29/doc-iihnzhfz2521482.shtml

当事人已经同意和解，咱们就没有闹的必要了

**Comment by bvegetas** [comment]
在此事件之前网易游戏就已经是996了（https://github.com/996icu/996.ICU/tree/master/blacklist），以后仍然要对网易游戏保持警惕

**Comment by wangxingkang** [comment]
当事人已和解，关闭issues
