### ISSUE TITLE
996.icu  slack频道,计划在996.icu一周年进行评奖活动

### ISSUE THREAD

**Issue by VincentWallace8012** [CPdogson/996action#125]
响应之前在 996.icu github频道 @NicofnCHINA 提出的建议
https://996icu.slack.com/
有人开了" 996年度评奖"频道. 
邀请链接  
https://join.slack.com/t/996icu/shared_invite/enQtNjI0MjEzMTUxNDI0LTA5NTc3MTk0MDRlMzIzNTI3ZDk1Y2IxNzQzZmM0NGQzNmI0NDA3MWE2ZWQyY2RlNjhkN2ViYjYyMDAzMGVmNjQ

计划996.icu运动开启一周年之际进行周年评奖
slack频道管理员认为.
因为该类评奖需要数据统计和大家投票评选.活动需要大量打酱油围观的码农们积极参与
目前人数少得让人尴尬.
目前距离996icu一周年 还有3个月.
请大家广而告知通知其他人加入slack频道发言响应.

**Comment by yeningyuan08** [comment]
现在996action.com怎么了

**Comment by yeningyuan08** [comment]
关键从哪拉码农,大家都在996,更何况我只是一个中学生(可以拉拢学生阶级)
