### ISSUE TITLE
建议增加律师互助板块

### ISSUE THREAD

**Issue by laziobird** [CPdogson/996action#18]
考虑更实际帮受害者解决维权问题，律师能更好、更专业答疑解惑，提供有价值帮助。
希望能增加律师互助板块，让更多的全国公益律师，热心律师帮助大家。
推荐一位成都热心的卢律师，这是他的个人介绍：
卢思位律师简介
 
律师执业证号：15101200610756109
擅长领域：公司法、合同法、金融法、刑事诉讼及人权案件
 
基本背景
卢思位律师毕业于华东政法学院，擅长于金融法、公司法、合同法、刑事辩护及人权案件，曾供职于证券公司、金融租赁公司及信托公司，对于股东纠纷、合同纠纷、企业并购、财产信托、私募基金管理均有很强的实践操作能力。自2013年起，卢思位律师开始关注公众事件，对于劳工权益和言论自由案件多有涉足，积累了较为丰富的诉讼经验。
代理的典型诉讼及非诉案件
中国首例“阳光私募”信托投资纠纷案；
中国首例宣告死亡保险合同纠纷案；
某“三板”上市公司股权清理案；
华融资产管理公司川北片区资产处置案；
刘某与公司股权纠纷案；
成都“纪念酒案”……
执业信念  
律师不应该仅仅是一个咬文爵字的法匠，他应当努力让自己成为一个思想者、管理者、演说家、谈判专家、财务专家、心理大师和战术大师，同时他还应当具有悲天悯人的普世情怀。

他的联系方式：http://luxu19730109@gmail.com
希望版主能看到我的建议，谢谢！

**Comment by CPdogson** [comment]
非常感谢您的建议。

对于律师这块我一直很谨慎。因为这涉及到金钱利益，律师不好，损失也会由每一位劳动者承担。之前被闭源的996.law有律师互助板块，最终轮流为广告板块，还大言不愧同行禁止入内。我要对每一个观看我板块的人负责。

因为我无法通过只言片语和简短的介绍来认识一位律师。我曾经也在律师业内工作，我的执业经历告诉我这个世界上有很多不负责的律师。

如果你想介绍一位律师，我更希望你能让他本人来联系我，我们可以具体的谈一些事务，进行一些具体合作后，我想我才能认清一位律师。另外，如果是人权律师，我也需要和他聊聊风险相关的事宜。

**Comment by laziobird** [comment]
太好了，dogson，其实更希望律师朋友直接联系你。因为他们不是很懂github的。你的联系邮箱是？

**Comment by laziobird** [comment]
是这个邮箱么？CPdogson@protonmail.com

**Comment by CPdogson** [comment]
> 
> 
> 是这个邮箱么？[CPdogson@protonmail.com](mailto:CPdogson@protonmail.com)

是的
