### ISSUE TITLE
是否可以将此宣传渠道加入首页

### ISSUE THREAD

**Issue by githubmll** [CPdogson/996action#21]
![wx](https://user-images.githubusercontent.com/17825339/56355802-d20ff680-6209-11e9-8184-70cf469c0c2c.png)

**Comment by CPdogson** [comment]
首先非常感谢您之前对活动的宣传

996.action是依赖996.icu以及github/996icu存续的板块，我只能让你这个二维码存续在Issues页面。
如果你希望加入主页面，需要您先通过996.icu的PR。我也在尝试联系发起人，希望得到他的支持。

所以非常抱歉，目前很难让一个非官方的二维码添加于主界面。

**Comment by githubmll** [comment]
@CPdogson 理解，理解，感谢您的支持。
