### ISSUE TITLE
5月1日福报节，有没有人一起去阿里过节？

### ISSUE THREAD

**Issue by a595364628** [CPdogson/996action#29]
5月1日福报节，有没有人一起去阿里过节？举红色条幅 上面书写 欢度五一福报节  现场活动拍照并发给媒体或者大V

**Comment by a595364628** [comment]
有人愿意去的话 请联系我 1552409517@qq.com

**Comment by JacksonJack123456** [comment]
给阿里寄一个劳动法文件的快递！

**Comment by a595364628** [comment]
> 给阿里寄一个劳动法文件的快递！

没个卵用，他们不是不知道法律。得结结实实臊他们一把 才有点用

**Comment by a595364628** [comment]
这种行为太怂了，得在法律允许范围内结结实实臊他们一把。我在杭州，可以组织少数人去 阿里举条幅 欢度五一福报节。也可送锦旗：法律不关键，996要实现

 

 ------------------ 原始邮件 ------------------
  发件人: "JacksonJack123456"<notifications@github.com>;
 发送时间: 2019年4月22日(星期一) 下午2:33
 收件人: "CPdogson/996action"<996action@noreply.github.com>;
 抄送: "王逸凡"<1552409517@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [CPdogson/996action] 5月1日福报节，有没有人一起去阿里过节？ (#29)

 

 
给阿里寄一个劳动法文件的快递！

**Comment by CPdogson** [comment]
> 
> 这种行为太怂了，得在法律允许范围内结结实实臊他们一把。我在杭州，可以组织少数人去 阿里举条幅 欢度五一福报节。也可送锦旗：法律不关键，996要实现
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "JacksonJack123456"<notifications@github.com>; 发送时间: 2019年4月22日(星期一) 下午2:33 收件人: "CPdogson/996action"<996action@noreply.github.com>; 抄送: "王逸凡"<1552409517@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [CPdogson/996action] 5月1日福报节，有没有人一起去阿里过节？ (#29) 给阿里寄一个劳动法文件的快递！ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

首先我不反对，你也可以在我的板块自由讨论。

如果你想进行，希望你可以帮忙做好合法性分析、实际可行性分析、战略规划等等，一项活动的策划并不是仅凭一句话，而是需要传播，需要真正的行动。策划一个这样的大行动，光风险分析和应对策略就要写几千字。如果你需要帮助，我也愿意帮助你。

另附
[随笔：至我那些爱泼冷水的朋友们](https://github.com/CPdogson/996action/blob/master/Essay.md)

**Comment by a595364628** [comment]
我思考了一下，就算我们拒不承认，也可能会被扣上违法行为的帽子。但是送锦旗是没问题的：法律不关键，996要实现。这是马云的原话，不构成诽谤。我的建议你可以参考一下

  

 ------------------ 原始邮件 ------------------
  发件人: "996.law"<notifications@github.com>;
 发送时间: 2019年4月22日(星期一) 下午4:18
 收件人: "CPdogson/996action"<996action@noreply.github.com>;
 抄送: "王逸凡"<1552409517@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [CPdogson/996action] 5月1日福报节，有没有人一起去阿里过节？ (#29)

 

  
这种行为太怂了，得在法律允许范围内结结实实臊他们一把。我在杭州，可以组织少数人去 阿里举条幅 欢度五一福报节。也可送锦旗：法律不关键，996要实现
…
------------------ 原始邮件 ------------------ 发件人: "JacksonJack123456"notifications@github.com; 发送时间: 2019年4月22日(星期一) 下午2:33 收件人: "CPdogson/996action"996action@noreply.github.com; 抄送: "王逸凡"1552409517@qq.com; "Author"author@noreply.github.com; 主题: Re: [CPdogson/996action] 5月1日福报节，有没有人一起去阿里过节？ (#29) 给阿里寄一个劳动法文件的快递！ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
 
首先我不反对，如果你想进行，希望你可以帮忙做好合法性分析、实际可行性分析、战略规划等等
 
另附
随笔：至我那些爱泼冷水的朋友们

**Comment by CPdogson** [comment]
> 
> 我思考了一下，就算我们拒不承认，也可能会被扣上违法行为的帽子。但是送锦旗是没问题的：法律不关键，996要实现。这是马云的原话，不构成诽谤。我的建议你可以参考一下
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "996.law"<notifications@github.com>; 发送时间: 2019年4月22日(星期一) 下午4:18 收件人: "CPdogson/996action"<996action@noreply.github.com>; 抄送: "王逸凡"<1552409517@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [CPdogson/996action] 5月1日福报节，有没有人一起去阿里过节？ (#29) 这种行为太怂了，得在法律允许范围内结结实实臊他们一把。我在杭州，可以组织少数人去 阿里举条幅 欢度五一福报节。也可送锦旗：法律不关键，996要实现 … ------------------ 原始邮件 ------------------ 发件人: "JacksonJack123456"notifications@github.com; 发送时间: 2019年4月22日(星期一) 下午2:33 收件人: "CPdogson/996action"996action@noreply.github.com; 抄送: "王逸凡"1552409517@qq.com; "Author"author@noreply.github.com; 主题: Re: [CPdogson/996action] 5月1日福报节，有没有人一起去阿里过节？ (#29) 给阿里寄一个劳动法文件的快递！ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. 首先我不反对，如果你想进行，希望你可以帮忙做好合法性分析、实际可行性分析、战略规划等等 另附 随笔：至我那些爱泼冷水的朋友们 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

送锦旗更像是一个个人行动，未来会有策划的
本次劳动法行动全名就是：
#向马云寄劳动法#行为艺术：向黑名单企业寄送建议信和劳动法、向白名单企业寄送感谢信和锦旗

**Comment by a595364628** [comment]
觉得可行的话，可纳入活动建议，另建议将首页的活动发起内容口语化更改一下，很多人一下看不懂，影响传播
 
 
 
背景说明
 
阿里巴巴马云和京东刘强东前一段时间对996工作制发表了看法。马云声称996是员工的福报，法律不是关键，而刘强东则声称不996的不是我兄弟。
 
对于996的违法行为，国内互联网大佬表示了支持。这种对于违法并且不人道的行为的支持，会继续恶化国内IT行业和其他行业的就业环境，为了我们自己，
 
为了我们的家庭，为了我们后代的生存环境，我们必须保障我们的权力。值五月一日国际劳动节和五月四日五四运动一百周年之际，现发起此次非暴力对抗活动的
 
建议。
 
活动说明
 
为了保证此次对抗活动参与者的安全，此次对抗活动必须严密合法。激进者表示应当游行，然而游行活动需要进行批准，相信公安部门难以批准这样的活动。
 
强硬游行的话，现场失控和后续报复不能保证参与者的人身安全。996.action活动的发起者CPdogson提议寄锦旗和寄劳动法的行动，然而这样的行动也有弊病，
 
阿里巴巴和京东拒收的话我们什么目的也达不到。
 
故在此提议，反向讽刺是可行的行动。更改五月一日劳动节为五一福报节，更改五月四日青年节为五月四日兄弟节。于当天在微博，朋友圈和其他社交平台庆祝
 
更名后的节日引起话题和讨论，酝酿舆论施压。另在杭州和北京等地，举行集会庆祝活动，举横幅“庆祝”此次活动，现场活动照片发送社交平台和大v及媒体。
 
法律可行性分析
  
 
寄送锦旗和劳动法不违法，996.action活动的发起者CPdogson的可行性分析已经进行了说明。

 
 
节日名称生成和更改并不违法。参考三八妇女节更改为女神节。

 
 
线下集会庆祝活动也不违法。

**Comment by drk74** [comment]
拜托填写996问卷,  一个关于996的调查; 
 https://wj.qq.com/s2/3585188/89ff/?from=timeline&isappinstalled=0
