### ISSUE TITLE
#向马云寄劳动法# 关于寄送劳动法的知乎文章+问题已提。为活动预热。

### ISSUE THREAD

**Issue by ame017** [CPdogson/996action#37]
[如何看待#5月4日向马云寄送劳动法#这一行为艺术？](https://www.zhihu.com/question/321181067)
[向马云寄送劳动法！继996.ICU之后又一行为艺术。-知乎文章](https://zhuanlan.zhihu.com/p/63243554)

**Comment by CPdogson** [comment]
非常感谢您的宣传！

你的知乎名字让我想起我以前玩舰可厉害了，最后大四下半学期吃不起饭2000R给卖了。

**Comment by ame017** [comment]
@CPdogson 文章已经被轮子哥翻牌子了。这波宣传基本宣传出去了，看看怎么打这副牌吧。加油。
vczh的想法 - 知乎
https://www.zhihu.com/pin/1103623665886863360

**Comment by CPdogson** [comment]
> 
> 
> @CPdogson 文章已经被轮子哥翻牌子了。这波宣传基本宣传出去了，看看怎么打这副牌吧。加油。
> vczh的想法 - 知乎
> https://www.zhihu.com/pin/1103623665886863360

刚刚我在slack中私聊轮子哥了
这个活动我记得好像他也参与了策划，挺多人参与策划的

这是大家的成果啊！

**Comment by ame017** [comment]
@CPdogson 辛苦了，我这边也会为我们的成果出一份力的，加油！

**Comment by CPdogson** [comment]
> 
> 
> @CPdogson 辛苦了，我这边也会为我们的成果出一份力的，加油！

“黑名单企业敢不收或者敢丢，我们就屎劲往资本家头上扣帽子，左一个侮辱国徽的帽子，右一个侮辱法律的帽子。”

这段话有人提出不得体，我原本的动机是为了更接地气。
说实话我也不知道改还是不改好。
如果答题的风向对这句话有很多不满，可以尝试进行修改。

**Comment by ame017** [comment]
@CPdogson 收到。我会尽量看每一条评论的。

**Comment by CPdogson** [comment]
> 
> 
> @CPdogson 收到。我会尽量看每一条评论的。

我也在看，话题热度上升的很快，目前看来没人带这句话的节奏

**Comment by yuanjingsong** [comment]
所以 为什么要在青年节寄劳动法？不应该是劳动节么？

**Comment by CPdogson** [comment]
> 
> 
> 所以 为什么要在青年节寄劳动法？不应该是劳动节么？

劳动节安排了信息公开的活动，所以把寄劳动法放在了青年节，另一个意图就是希望青年（学生）群体参与

[申请信息公开420会议共识](https://github.com/CPdogson/996action/blob/master/Gov-info/420meet.md)

**Comment by monkeyjill** [comment]
我也回答了这个知乎问题，小透明加入这次运动！ 希望大家以理智、守法的方式呼吁我们的权利！

**Comment by CPdogson** [comment]
> 
> 
> [如何看待#5月4日向马云寄送劳动法#这一行为艺术？](https://www.zhihu.com/question/321181067)
> [向马云寄送劳动法！继996.ICU之后又一行为艺术。-知乎文章](https://zhuanlan.zhihu.com/p/63243554)

这都能404，看来有个高赞回答是正确的

算了，冷静冷静，问问管理员哪里违规了，改改找别人再发吧。

可能是外链GitHub的原因，也可能是扣帽子的言论。

**Comment by ame017** [comment]
@CPdogson 我申诉了，知乎秒拒绝。而且不提供任何修改建议。无奈。

**Comment by jingjiniaojingji** [comment]
上面的几个链接好像都消失了 被删了吧？

**Comment by CPdogson** [comment]
> 
> 
> 上面的几个链接好像都消失了 被删了吧？

问题还没删，文章删了

**Comment by jingjiniaojingji** [comment]
国内被他们联合起来抵制了 如果实在不行 能不能先从国外入手 由外到内呢?至少国外国内两手抓吧...可惜我不是玩自媒体的 否则绝对宣传... 不过寄本书还是可以做到的。

**Comment by CPdogson** [comment]
> 
> 
> 国内被他们联合起来抵制了 如果实在不行 能不能先从国外入手 由外到内呢?至少国外国内两手抓吧...可惜我不是玩自媒体的 否则绝对宣传... 不过寄本书还是可以做到的。

国外记者找过我，但是由外至内我怕一顶境外势力的帽子扣头上

**Comment by jingjiniaojingji** [comment]
那要不就先尝试在国内搞 如果国内实在不给出路  那就没得选了 只能先从国外开始了(996.icu最先是从国外开始火的吧(不太确定)? 国内一开始是不是禁的?) 没办法 国内的那群人抱团抱的太紧了...




------------------ 原始邮件 ------------------
发件人: "996.law"<notifications@github.com>; 
发送时间: 2019年4月22日(星期一) 晚上11:05
收件人: "CPdogson/996action"<996action@noreply.github.com>; 
抄送: "荆棘鸟"<447452311@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [CPdogson/996action] 关于寄送劳动法的知乎文章+问题已提。为活动预热。 (#37)



 
国内被他们联合起来抵制了 如果实在不行 能不能先从国外入手 由外到内呢?至少国外国内两手抓吧...可惜我不是玩自媒体的 否则绝对宣传... 不过寄本书还是可以做到的。
  
国外记者找过我，但是由外至内我怕一顶境外势力的帽子扣头上

**Comment by jingjiniaojingji** [comment]
> > 国内被他们联合起来抵制了 如果实在不行 能不能先从国外入手 由外到内呢?至少国外国内两手抓吧...可惜我不是玩自媒体的 否则绝对宣传... 不过寄本书还是可以做到的。
> 
> 国外记者找过我，但是由外至内我怕一顶境外势力的帽子扣头上

那要不就先尝试在国内搞 如果国内实在不给出路  那就没得选了 只能先从国外开始了(996.icu最先是从国外开始火的吧(不太确定)? 国内一开始是不是禁的?) 没办法 国内的那群人抱团抱的太紧了...

**Comment by CPdogson** [comment]
> 
> 
> [如何看待#5月4日向马云寄送劳动法#这一行为艺术？](https://www.zhihu.com/question/321181067)
> [向马云寄送劳动法！继996.ICU之后又一行为艺术。-知乎文章](https://zhuanlan.zhihu.com/p/63243554)

我在知乎上没发过问题，如果知乎在搜索中屏蔽了一个问题，代表着什么？背后是知乎平台行为还是存在更大的力量？
我们这件事情有这么敏感吗......我是否需要重新评估这件事的风险和传播策略？

**Comment by jingjiniaojingji** [comment]
> > [如何看待#5月4日向马云寄送劳动法#这一行为艺术？](https://www.zhihu.com/question/321181067)
> > [向马云寄送劳动法！继996.ICU之后又一行为艺术。-知乎文章](https://zhuanlan.zhihu.com/p/63243554)
> 
> 我在知乎上没发过问题，如果知乎在搜索中屏蔽了一个问题，代表着什么？背后是知乎平台行为还是存在更大的力量？
> 我们这件事情有这么敏感吗......我是否需要重新评估这件事的风险和传播策略？

>有点 局座在B站上的一个一百多万访问量 留言量好几万的视频昨天被删了。昨天国务院给大家留了互联网+督促这么一个平台 我感觉是非常好的 建议咱们先暂停寄书行动吧 毕竟这事国家算是管了 愿意倾听网友的声音 那咱们还是通过国家提供的平台来发表咱们的意见 举报那些违法的企业吧。

**Comment by jingjiniaojingji** [comment]
> > > [如何看待#5月4日向马云寄送劳动法#这一行为艺术？](https://www.zhihu.com/question/321181067)
> > > [向马云寄送劳动法！继996.ICU之后又一行为艺术。-知乎文章](https://zhuanlan.zhihu.com/p/63243554)
> > 
> > 
> > 我在知乎上没发过问题，如果知乎在搜索中屏蔽了一个问题，代表着什么？背后是知乎平台行为还是存在更大的力量？
> > 我们这件事情有这么敏感吗......我是否需要重新评估这件事的风险和传播策略？
> 
> > 有点 局座在B站上的一个一百多万访问量 留言量好几万的视频昨天被删了。昨天国务院给大家留了互联网+督促这么一个平台 我感觉是非常好的 建议咱们先暂停寄书行动吧 毕竟这事国家算是管了 愿意倾听网友的声音 那咱们还是通过国家提供的平台来发表咱们的意见 举报那些违法的企业吧。

另附国务院互联网+督促网址: http://tousu.www.gov.cn/dc/index.htm

**Comment by CPdogson** [comment]
> 
> 
> > > > [如何看待#5月4日向马云寄送劳动法#这一行为艺术？](https://www.zhihu.com/question/321181067)
> > > > [向马云寄送劳动法！继996.ICU之后又一行为艺术。-知乎文章](https://zhuanlan.zhihu.com/p/63243554)
> > > 
> > > 
> > > 我在知乎上没发过问题，如果知乎在搜索中屏蔽了一个问题，代表着什么？背后是知乎平台行为还是存在更大的力量？
> > > 我们这件事情有这么敏感吗......我是否需要重新评估这件事的风险和传播策略？
> > 
> > 
> > > 有点 局座在B站上的一个一百多万访问量 留言量好几万的视频昨天被删了。昨天国务院给大家留了互联网+督促这么一个平台 我感觉是非常好的 建议咱们先暂停寄书行动吧 毕竟这事国家算是管了 愿意倾听网友的声音 那咱们还是通过国家提供的平台来发表咱们的意见 举报那些违法的企业吧。
> 
> 另附国务院互联网+督促网址: http://tousu.www.gov.cn/dc/index.htm

非常感谢您的支持
只不过你没发现，建设中早有这一链接了吗，哈哈~我发现的比你快
开个玩笑

**Comment by jingjiniaojingji** [comment]
> > > > > [如何看待#5月4日向马云寄送劳动法#这一行为艺术？](https://www.zhihu.com/question/321181067)
> > > > > [向马云寄送劳动法！继996.ICU之后又一行为艺术。-知乎文章](https://zhuanlan.zhihu.com/p/63243554)
> > > > 
> > > > 
> > > > 我在知乎上没发过问题，如果知乎在搜索中屏蔽了一个问题，代表着什么？背后是知乎平台行为还是存在更大的力量？
> > > > 我们这件事情有这么敏感吗......我是否需要重新评估这件事的风险和传播策略？
> > > 
> > > 
> > > > 有点 局座在B站上的一个一百多万访问量 留言量好几万的视频昨天被删了。昨天国务院给大家留了互联网+督促这么一个平台 我感觉是非常好的 建议咱们先暂停寄书行动吧 毕竟这事国家算是管了 愿意倾听网友的声音 那咱们还是通过国家提供的平台来发表咱们的意见 举报那些违法的企业吧。
> > 
> > 
> > 另附国务院互联网+督促网址: http://tousu.www.gov.cn/dc/index.htm
> 
> 非常感谢您的支持
> 只不过你没发现，建设中早有这一链接了吗，哈哈~我发现的比你快
> 开个玩笑

哈哈哈...
