### ISSUE TITLE
可以顺便反映一下公司不交公积金的事情吗

### ISSUE THREAD

**Issue by huangtingxuan** [CPdogson/996action#39]

**Comment by ame017** [comment]
公积金和五险不同，不是法律强制缴纳的。

**Comment by PetalsOnaWet** [comment]
> 公积金和五险不同，不是法律强制缴纳的。

这个是必须要缴纳的

**Comment by PetalsOnaWet** [comment]
建议带上合同，咨询下仲裁机构，询问需要什么证据，收集证据直接仲裁

**Comment by CPdogson** [comment]
建议专至996.law讨论该问题，可能会遇到法律大佬

我对公积金这块了解并不多，我本人也是没有公积金的
