### ISSUE TITLE
#向马云寄劳动法# 51劳动节给马云寄劳动法！给白名单企业寄锦旗！搞个行为艺术！

### ISSUE THREAD

**Issue by JacksonJack123456** [CPdogson/996action#41]

**Comment by hysios** [comment]
不赞成，首先没什么用，因为寄不到目标去，都会被拦截，其次只指对单一目标，还不如搞一个，一日罢工

**Comment by JacksonJack123456** [comment]
你有权拒收！

**Comment by JacksonJack123456** [comment]
要罢工你自己去罢工！不要采取过激的手段！

**Comment by CPdogson** [comment]
> 
> 
> 不赞成，首先没什么用，因为寄不到目标去，都会被拦截，其次只指对单一目标，还不如搞一个，一日罢工

大家目标都是维护休息制度、维护法治，如果朋友你愿意发起合适的合法行动，我当然支持。
如果朋友你期待，那请带上你的《分析》、《战略》和《规划》进行RP，而不是一句话而已。

但我希望朋友你不要对其他人泼冷水，这毫无意义。

附：
[随笔：至我那些爱泼冷水的朋友们](https://github.com/CPdogson/996action/blob/master/Essay.md)

**Comment by CPdogson** [comment]
> 
> 
> _No description provided._

活动的全名叫做：
#向马云寄劳动法#行为艺术：向黑名单企业寄送建议信和劳动法、向白名单企业寄送感谢信和锦旗
未来会有的，我们要一步步的进行

**Comment by hysios** [comment]
摆工算什么过激手段，再正常不过的权利了的，能不能组织成功才是问题，而不是连想都不敢想，花大力气时间，赢得共识来实现有威慑的目标。当然我也期待你们的行动，我只不过是提些意见并没有泼冷水的意思

**Comment by ame017** [comment]
@hysios 目前的情况来看，很多很多人，根本都不知道996是违法的，你拉他们去罢工，他们除了觉得你有病，没有别的想法了。“学医救不了中国人”，不从根本上改变大家的思维，是没用的。

**Comment by qihong1983** [comment]
5月10日，是阿里巴巴的阿里日

**Comment by hysios** [comment]
就约定一个日子，在家休息一天，就行了，也不需要上街，也不需要游行，就当给自己放一天的假

**Comment by VitoMispJT** [comment]
😄😄😄

**Comment by sogo123** [comment]
心通达OA团队，赞助1000元支持本次活动，QQ11201403，请联系我。

**Comment by CPdogson** [comment]
> 
> 
> 心通达OA团队，赞助1000元支持本次活动，QQ11201403，请联系我。

不建议您这样做，大额的捐助无论双方谁被欺骗都是一种巨大损失。如果您必须这样做，可以减少捐款金额，比如9.96元这样的数字。如果必须捐赠大额，请索取票据(购买物件的发票和邮寄发票)后进行捐赠。

**Comment by sogo123** [comment]
> > 心通达OA团队，赞助1000元支持本次活动，QQ11201403，请联系我。
> 
> 不建议您这样做，很难保证联系您的是否是骗子。如果您必须这样做，请在对方出示相关票据后给予款项。

好的、谢谢。我是想可以给到组织者，用于买书、邮寄。

**Comment by CPdogson** [comment]
> 
> 
> > > 心通达OA团队，赞助1000元支持本次活动，QQ11201403，请联系我。
> > 
> > 
> > 不建议您这样做，很难保证联系您的是否是骗子。如果您必须这样做，请在对方出示相关票据后给予款项。
> 
> 好的、谢谢。我是想可以给到组织者，用于买书、邮寄。

据我所知几个QQ群为载体的组织已经被解散了，联系上您的很可能是骗子，请务必小心。如果您确定的话我可以在slack群内宣传，但我不保证联系您的是否是行动者/组织者。
