### ISSUE TITLE
zssb

### ISSUE THREAD

**Issue by leiben161208** [CPdogson/996action#42]
zssb

**Comment by CyrilPWong** [comment]
马老师的弟子？

**Comment by JacksonJack123456** [comment]
马云牌鸡汤中毒太深！没救了！

**Comment by withcancer** [comment]
试看国内什么样的人才会动不动联想政治？
一个正常诉求的实现到你这成了煽动？
701水军给你多少我给双倍!
1块！

**Comment by lby1992** [comment]
@leiben161208 希望你将来不要和染香那厮一样

**Comment by CPdogson** [comment]
首先我要明确，这个话题的所有动作都是楼主自己进行的，包括修改和关闭问题，这在GitHub上都有记录。

我个人不会关闭这个话题，如果有人继续讨论该话题我也不会阻止——这就是我板块的自由言论。

其次，我并不打算煽动任何人，我只是做一个简单的行动罢了。另外所有关于行动的组织策划和讨论修改都使用slack进行，slack的聊天记录均在GitHub上进行公开——也就是说我的活动从头到尾都是透明的。
[活动讨论记录](https://github.com/simon300000/996icu-slack-recorder)
