### ISSUE TITLE
发个购买链接

### ISSUE THREAD

**Issue by pzZZZZ** [CPdogson/996action#44]
我这边看到的都是几十块一本啊

**Comment by CPdogson** [comment]
首先，我要明确法律出版社的劳动法官方定价为5元，一般价格就是2~3元

关于购买链接，可以在此处贴出，但作为发起人，我明确不参与任何商业行动，也就是说广告我是不能打的。

两个常规电商平台我都看了，一家2.5元一家3元，批量购买都有优惠

附：
书号：7509355589  
条码：9787509355589  
图书名称：中华人民共和国劳动法（2014年最新版 附司法解释一、二、三、四）   
定价：5.00
作者：中国法制出版社  
版别：中国法制  
出版日期：2014-7-1

书名： 中华人民共和国劳动法（*修正版 附相关司法解释） 
书号： 9787519708443 
定价： 6.00 
作者/编者： 法律出版社 
出版社： 法律出版社 
出版时间： 2019年01月

**Comment by vvvv3** [comment]
taobao搜索下就有了。。。。 ![image](https://user-images.githubusercontent.com/49094846/56492459-75208300-651e-11e9-8434-331a5d8fc676.png)

**Comment by monkeyjill** [comment]
> taobao搜索下就有了。。。。 ![image](https://user-images.githubusercontent.com/49094846/56492459-75208300-651e-11e9-8434-331a5d8fc676.png)

这是天猫链接吧，，，当当旗舰店，利润还是归老马？
看到有的说要在淘宝店买，不让某云赚这个钱哎，，，

我准备明天去实体书店买

**Comment by vvvv3** [comment]
> > taobao搜索下就有了。。。。 ![image](https://user-images.githubusercontent.com/49094846/56492459-75208300-651e-11e9-8434-331a5d8fc676.png)
> 
> 这是天猫链接吧，，，当当旗舰店，利润还是归老马？
> 看到有的说要在淘宝店买，不让某云赚这个钱哎，，，
> 
> 我准备明天去实体书店买

还有这种操作。。。

**Comment by monkeyjill** [comment]
> > > taobao搜索下就有了。。。。 ![image](https://user-images.githubusercontent.com/49094846/56492459-75208300-651e-11e9-8434-331a5d8fc676.png)
> > 
> > 
> > 这是天猫链接吧，，，当当旗舰店，利润还是归老马？
> > 看到有的说要在淘宝店买，不让某云赚这个钱哎，，，
> > 我准备明天去实体书店买
> 
> 还有这种操作。。。

如果不方便去实体店买，买这个便宜的也行。但是策划者说过了希望大家不要买贵了，给资本家更多赚我们钱的机会。
3块钱再加上6块钱邮费，一共9元，再加上寄挂号信的钱，总之不要花过多的钱。毕竟大家挣钱不容易嘛

**Comment by pzZZZZ** [comment]
OK
