### ISSUE TITLE
赞成成立一个组织，力量可以集中体现出来。

### ISSUE THREAD

**Issue by keenlovelife** [CPdogson/996action#45]
赞成成立一个组织，力量可以集中体现出来，并且有实际效果；目前996.IUC 开始进入大众视野，但是仍只是讨论和思考，并没有任何实际行动和实际效果，除了爆出来各种猝死等新闻，其实并没有任何有利行动或有利成果呈现。

成立自己的组织后，才能真正保护自己的利益。就好像公务员们会把自己的福利利益搞得多多的，成立自己的组织之后，才会关注和保护自己的利益。

但是成立的组织的细节需要慎重的讨论和分析，盲目行动可能夭折。

**Comment by CPdogson** [comment]
您好

[成立组织的可行性分析](https://github.com/CPdogson/996action/blob/master/organization.md)

[讨论：我们是否要成立组织](https://github.com/CPdogson/996action/issues/5)

请在以上链接进行PR或者讨论，谢谢
