### ISSUE TITLE
#向马云寄劳动法# 给 XXX寄劳动法扇脸的行为，应区分出经组织后的统一寄送和个人寄送行为。

### ISSUE THREAD

**Issue by keenlovelife** [CPdogson/996action#46]
给 XXX寄劳动法扇脸的行为，应区分出经组织后的统一寄送和个人寄送行为。

个人寄送无法控制其行为，不能确定哪天寄送的，可能寄错了地方，也可能寄错了东西，万一真寄成刀片，容易给 996 组织抹黑。

统一寄送，需事前公示，和事后公示。

公示寄送内容和名单，表明这是一场行为艺术，未包含任何其他含义，仅仅是给 XX 寄个劳动法宪法什么的就这么简单；寄送过程可以拍照片发视频进行直播。

事后，就是快递单显示出寄送结果（签收、拒签、其他），或显示出寄送结果某些天过后， 进行后续跟踪汇总，我们虽不指望真的能寄到马云手上，但是对结果进行一下统计，可以检查寄送行为产生的结果如何。

**Comment by CPdogson** [comment]
您好

[#向马云寄劳动法#5月4日青年节一起向马云寄劳动法吧！](https://github.com/CPdogson/996action/blob/master/black-and-white.md)

对于捣乱份子，无论成立组织与否，我们都无法进行阻止。

对于活动我描述的非常清楚，我意图是发起个人行动。但我不反对任何一个人进行组织性活动，你可以自行发起组织，我不干涉。

在传播一栏也叙述了你提到的一些信息。

对于成立组织我在另一个issues回复了你，我们有讨论成立组织的问题串。

谢谢您的支持！
