### ISSUE TITLE
不应该是助理或者秘书来接收快递么？

### ISSUE THREAD

**Issue by ShaGou** [CPdogson/996action#48]

**Comment by CPdogson** [comment]
行为艺术，顾名思义，行为表达一种艺术，本次的行为是“寄出”，而不是结果“寄到”，我要做的也不是结果艺术。
行为艺术的初衷并非达成直接结果，而是通过行为表达艺术，通过艺术进行传播。
也就是我不会期待这本劳动法不可能到达马云手上，我的期待是大众热议这件事情，从而传播996icu和996action的理念，聚集支持我们的劳动者。
