### ISSUE TITLE
关于五月一日和五月四日进行祈福活动，晒自己的加班和寄劳动法的照片

### ISSUE THREAD

**Issue by a595364628** [CPdogson/996action#49]
### 背景说明

阿里巴巴马云和京东刘强东前一段时间对996工作制发表了看法。马云声称996是员工的福报，法律不是关键，而刘强东则声称不996的不是我兄弟。

对于996的违法行为，国内互联网大佬表示了支持。这种对于违法并且不人道的行为的支持，会继续恶化国内IT行业和其他行业的就业环境，为了我们自己，

为了我们的家庭，为了我们后代的生存环境，我们必须保障我们的权力。值五月一日国际劳动节和五月四日五四运动一百周年之际，现发起此次非暴力对抗活动的

建议。

### 活动说明

为了保证此次对抗活动参与者的安全，此次对抗活动必须严密合法。激进者表示应当游行，然而游行活动需要进行批准，相信公安部门难以批准这样的活动。

强硬游行的话，现场失控和后续报复不能保证参与者的人身安全。996.action活动的发起者CPdogson提议寄锦旗和寄劳动法的行动，然而这样的行动也有弊病，

阿里巴巴和京东拒收的话我们什么目的也达不到。

故在此提议，反向讽刺是可行的行动。更改五月一日劳动节为五一福报节，更改五月四日青年节为五月四日兄弟节。于当天在微博，朋友圈和其他社交平台庆祝

更名后的节日引起话题和讨论，酝酿舆论施压。另在杭州和北京等地，举行集会庆祝活动，举横幅“庆祝”此次活动，现场活动照片发送社交平台和大v及媒体。

### 法律可行性分析

1. 寄送锦旗和劳动法不违法，996.action活动的发起者CPdogson的可行性分析已经进行了说明。

2. 节日名称生成和更改并不违法。参考三八妇女节更改为女神节。

3. 线下集会庆祝活动也不违法。

**Comment by CPdogson** [comment]
''阿里巴巴和京东拒收的话我们什么目的也达不到。''

解释一下，行为艺术，顾名思义，行为表达一种艺术，本次的行为是“寄出”，而不是结果“寄到”，我要做的也不是结果艺术。
行为艺术的初衷并非达成直接结果，而是通过行为表达艺术，通过艺术进行传播。
也就是我不会期待这本劳动法不可能到达马云手上，我的期待是大众热议这件事情，从而传播996icu和996action的理念，聚集支持我们的劳动者。

其他观点你自由发挥，另外超过一定人数线下集会是需要报备的，具体法律条款和历史信息自行翻阅。

**Comment by a595364628** [comment]
庆祝活动也需报备？卧槽
  

 

 ------------------ 原始邮件 ------------------
  发件人: "996.law"<notifications@github.com>;
 发送时间: 2019年4月22日(星期一) 晚上7:35
 收件人: "CPdogson/996action"<996action@noreply.github.com>;
 抄送: "王逸凡"<1552409517@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [CPdogson/996action] 关于五月一日和五月四日非暴力对抗及庆祝活动发起建议 (#49)

 

 
''阿里巴巴和京东拒收的话我们什么目的也达不到。''
 
我解释过很多次行为艺术不是结果艺术，这种行为是劳动者寄出行为，寄出行为是一种艺术，我们通过这种艺术来宣传我们的理念，聚集支持我们的人群。而不是收到的结果。
 
其他观点你自由发挥，另外超过一定人数线下集会是需要报备的，具体法律条款和历史信息自行翻阅。

**Comment by CPdogson** [comment]
> 
> 庆祝活动也需报备？卧槽
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "996.law"<notifications@github.com>; 发送时间: 2019年4月22日(星期一) 晚上7:35 收件人: "CPdogson/996action"<996action@noreply.github.com>; 抄送: "王逸凡"<1552409517@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [CPdogson/996action] 关于五月一日和五月四日非暴力对抗及庆祝活动发起建议 (#49) ''阿里巴巴和京东拒收的话我们什么目的也达不到。'' 我解释过很多次行为艺术不是结果艺术，这种行为是劳动者寄出行为，寄出行为是一种艺术，我们通过这种艺术来宣传我们的理念，聚集支持我们的人群。而不是收到的结果。 其他观点你自由发挥，另外超过一定人数线下集会是需要报备的，具体法律条款和历史信息自行翻阅。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

因为是庆祝活动还是游行示威不是个人定义的，而是由官方认定的。
也就是解释权不在个体手中。

**Comment by a595364628** [comment]
那就五月一日福报节或者五月四日当天 进行祈福活动，晒自己的加班和寄劳动法的照片。祈求福报，发布在社交平台
  

 

 ------------------ 原始邮件 ------------------
  发件人: "996.law"<notifications@github.com>;
 发送时间: 2019年4月22日(星期一) 晚上7:42
 收件人: "CPdogson/996action"<996action@noreply.github.com>;
 抄送: "王逸凡"<1552409517@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [CPdogson/996action] 关于五月一日和五月四日非暴力对抗及庆祝活动发起建议 (#49)

 

  
庆祝活动也需报备？卧槽
…
------------------ 原始邮件 ------------------ 发件人: "996.law"notifications@github.com; 发送时间: 2019年4月22日(星期一) 晚上7:35 收件人: "CPdogson/996action"996action@noreply.github.com; 抄送: "王逸凡"1552409517@qq.com; "Author"author@noreply.github.com; 主题: Re: [CPdogson/996action] 关于五月一日和五月四日非暴力对抗及庆祝活动发起建议 (#49) ''阿里巴巴和京东拒收的话我们什么目的也达不到。'' 我解释过很多次行为艺术不是结果艺术，这种行为是劳动者寄出行为，寄出行为是一种艺术，我们通过这种艺术来宣传我们的理念，聚集支持我们的人群。而不是收到的结果。 其他观点你自由发挥，另外超过一定人数线下集会是需要报备的，具体法律条款和历史信息自行翻阅。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
 
因为是庆祝活动还是游行示威不是个人定义的，而是由官方认定的。
也就是解释权不在个体手中。
