### ISSUE TITLE
English Please

### ISSUE THREAD

**Issue by us** [CPdogson/996action#56]
### What is the problem with Chinese README's

Firstly, we congratulate you for getting so much star by sharing this repository with humanity.

But it is very disappointing for non-Chinese speakers when one couldn't understand what a trending repository is about.

When we see such a repo on trending, our minds are blurring like Gollum's.

![Gollum Image](https://media.giphy.com/media/V4uGHRgz0zi6Y/giphy-downsized-large.gif)

There is a way **you can help** to solve this disappointment which I believe is experienced by many people who want to know more about your valuable work and appreciate it.

### What we want:
 - Please add English translation of your README so you are sharing your work and knowledge with more people.

### How this will help you:
 - More feedback to fix and improve your project.
 - New ideas about your project.
 - Greater fame.
 - ![SungerBob Image](https://media.giphy.com/media/3o7absbD7PbTFQa0c8/source.gif)

---

_“Sharing knowledge is the most fundamental act of friendship. Because it is a way you can give something without loosing something.”_

_**— Richard Stallman**_

**Thank you!**	

 > This issue created by [us/english-please](github.com/us/english-please) script. Please report on any error. Thank you!

**Comment by CPdogson** [comment]
Thank you for your support, I am looking for someone to translate. You can use Google Translate during this time.

**Comment by will1942** [comment]
I can translate Chinese to English(if there are no much technology terms) or English to Chinese. If you have something to translate, you can send it to will1942@protonmail.com.

**Comment by timruning** [comment]
Thank you we will try to translate it hah

**Comment by shingz96** [comment]
LOL. Those 996 repo is actually about the China company(s) that promotes their employee to work from 9am to 9pm (Monday to Saturday). Basically is the worker plan to fight for their rights now to work 8 hours in 5 days (Monday to Friday).

**Comment by nirui** [comment]
There is a chance that you guys are wasting your time and love for a robot.

https://github.com/search?q=English+Please&type=Issues
