### ISSUE TITLE
在遥远的开曼岛，有一种名叫CE鸥的鸟，长得有点像鹦鹉，嘴里一直不停发出996好啊，996对啊的叫声，听起来像人的声音，但是大家伙儿觉得怎么听都不想人话啊！

### ISSUE THREAD

**Issue by JacksonJack123456** [CPdogson/996action#59]
在遥远的开曼岛，有一种名叫CE鸥的鸟，长得有点像鹦鹉，嘴里一直不停发出996好啊，996对啊的叫声，听起来像人的声音，但是大家伙儿觉得怎么听都不想人话啊！

**Comment by CPdogson** [comment]
首先感谢您为反对996发声

非常抱歉，如果缺乏实质问题/建设性意见的话，会在24小时后关闭Issues。
