### ISSUE TITLE
线下发放劳动法活动建议

### ISSUE THREAD

**Issue by VulperVoid** [CPdogson/996action#65]
建议可以众筹采购劳动法，在多城市办公密集区域向工作者发放，包括但不限于IT从业者、金融从业者、销售人员、建筑从业者等劳动者。目的在于扩展项目的线下影响力，来联合更多可联合的同志。
要点如下：
1、定制996ICU印章，每本劳动法上加盖标记
2、建立低门槛线上平台，供各行业人加入讨论，如果能建成，可以把地址一并印在发放的劳动法上
3、设计加班状况调查问卷(匿名)，发放劳动法后询问领取人是否愿意帮助调查，全凭自愿，搜集到的统计信息可以在将来更多活动中发挥作用
4、尽量避开居民区，避免贪小便宜的市民恶意领取变卖废品

**Comment by CPdogson** [comment]
这是一个不错的建议，但我目前无法解决我的匿名身份和合法众筹的冲突，也就是我无法使用一个匿名身份在众筹平台发起众筹。如果你愿意的话可以发起类似的活动，我很乐意在issues上帮你宣传。

**Comment by 328849098** [comment]
支持

**Comment by CPdogson** [comment]
这类活动组织需要大量的人力物力，如果有10位志愿者愿意自费参与的话，我想是有可能的

如果需要压缩成本，可以放在校招的时候于人才市场发放

**Comment by 328849098** [comment]
qq群在搞这个活动，地址北京，合适的请加入，群号:806535337

**Comment by 328849098** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/11973902/56717345-04bc7080-676f-11e9-8e46-0e934f3cbe28.png">

**Comment by 328849098** [comment]
qq群组在线讨论，群号:806535337


------------------ 原始邮件 ------------------
发件人: "996.law"<notifications@github.com>;
发送时间: 2019年4月25日(星期四) 下午3:24
收件人: "CPdogson/996action"<996action@noreply.github.com>;
抄送: "寒霜戏影"<328849098@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [CPdogson/996action] 线下发放劳动法活动建议 (#65)




这类活动组织需要大量的人力物力，如果有10位志愿者愿意自费参与的话，我想是有可能的
 
如果需要压缩成本，可以放在校招的时候于人才市场发放

**Comment by CPdogson** [comment]
> 
> qq群组在线讨论，群号:806535337
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "996.law"<notifications@github.com>; 发送时间: 2019年4月25日(星期四) 下午3:24 收件人: "CPdogson/996action"<996action@noreply.github.com>; 抄送: "寒霜戏影"<328849098@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [CPdogson/996action] 线下发放劳动法活动建议 (#65) 这类活动组织需要大量的人力物力，如果有10位志愿者愿意自费参与的话，我想是有可能的 如果需要压缩成本，可以放在校招的时候于人才市场发放 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

您有除了QQ群以外的联系方式吗？我想具体了解一下活动的策划和进展

**Comment by rain512** [comment]
1.请实施活动的小伙伴们，一定，一定要注意安全。
大家都是程序员，线上个人情报注意保护，线下注意不法分子的利用。
2.希望海外程序员也加入进来。

今天的我们要发扬五四精神
前事不忘後事之師

**Comment by 328849098** [comment]
> > qq群组在线讨论，群号:806535337
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "996.law"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年4月25日(星期四) 下午3:24 收件人: "CPdogson/996action"[996action@noreply.github.com](mailto:996action@noreply.github.com); 抄送: "寒霜戏影"[328849098@qq.com](mailto:328849098@qq.com); "Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [CPdogson/996action] 线下发放劳动法活动建议 (#65) 这类活动组织需要大量的人力物力，如果有10位志愿者愿意自费参与的话，我想是有可能的 如果需要压缩成本，可以放在校招的时候于人才市场发放 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 您有除了QQ群以外的联系方式吗？我想具体了解一下活动的策划和进展

可以邮箱联系。目前进展
<img width="388" alt="image" src="https://user-images.githubusercontent.com/11973902/56858296-32d9c480-69aa-11e9-8713-2867bc0f0a74.png">

**Comment by 328849098** [comment]
> 1.请实施活动的小伙伴们，一定，一定要注意安全。
> 大家都是程序员，线上个人情报注意保护，线下注意不法分子的利用。
> 2.希望海外程序员也加入进来。
> 
> 今天的我们要发扬五四精神
> 前事不忘後事之師

已经了解到，不会大张旗鼓，每个人的募捐留名都是网名

**Comment by CPdogson** [comment]
> 
> 
> > > qq群组在线讨论，群号:806535337
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "996.law"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年4月25日(星期四) 下午3:24 收件人: "CPdogson/996action"[996action@noreply.github.com](mailto:996action@noreply.github.com); 抄送: "寒霜戏影"[328849098@qq.com](mailto:328849098@qq.com); "Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [CPdogson/996action] 线下发放劳动法活动建议 (#65) 这类活动组织需要大量的人力物力，如果有10位志愿者愿意自费参与的话，我想是有可能的 如果需要压缩成本，可以放在校招的时候于人才市场发放 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> > 
> > 您有除了QQ群以外的联系方式吗？我想具体了解一下活动的策划和进展
> 
> 可以邮箱联系。目前进展
> <img alt="image" width="388" src="https://user-images.githubusercontent.com/11973902/56858296-32d9c480-69aa-11e9-8713-2867bc0f0a74.png">

你们的邮箱是什么呢？我的邮箱是CPdogson@protonmail.com
你的邮箱是github名字@qq.com吗？如果确认的话我稍晚联系你们

**Comment by 328849098** [comment]
328849098@qq.com


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 996.law <notifications@github.com>
发送时间: 2019年4月28日 12:30
收件人: CPdogson/996action <996action@noreply.github.com>
抄送: 不入海 <328849098@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[CPdogson/996action] 线下发放劳动法活动建议 (#65)



   
qq群组在线讨论，群号:806535337
 …
 ------------------ 原始邮件 ------------------ 发件人: "996.law"notifications@github.com; 发送时间: 2019年4月25日(星期四) 下午3:24 收件人: "CPdogson/996action"996action@noreply.github.com; 抄送: "寒霜戏影"328849098@qq.com; "Comment"comment@noreply.github.com; 主题: Re: [CPdogson/996action] 线下发放劳动法活动建议 (#65) 这类活动组织需要大量的人力物力，如果有10位志愿者愿意自费参与的话，我想是有可能的 如果需要压缩成本，可以放在校招的时候于人才市场发放 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
您有除了QQ群以外的联系方式吗？我想具体了解一下活动的策划和进展
  
可以邮箱联系。目前进展
 
  
你们的邮箱是什么呢？我的邮箱是CPdogson@protonmail.com
 你的邮箱是github名字@qq.com吗？如果确认的话我稍晚联系你们

**Comment by huangfly** [comment]
> 806535337

这个群搜不到了？？

**Comment by VulperVoid** [comment]
> > 806535337
> 
> 这个群搜不到了？？

活动终止,群解散了

**Comment by huangfly** [comment]
加油，我支持你们，只是来晚了。




------------------ 原始邮件 ------------------
发件人: "Tsao Lee"<notifications@github.com>; 
发送时间: 2019年4月30日(星期二) 下午5:20
收件人: "CPdogson/996action"<996action@noreply.github.com>; 
抄送: "M-ZONE"<798677116@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [CPdogson/996action] 线下发放劳动法活动建议 (#65)



  
806535337
  
这个群搜不到了？？
  
活动终止,群解散了
