### ISSUE TITLE
很无聊的我就想建议刷个表情包

### ISSUE THREAD

**Issue by chensuoxin** [CPdogson/996action#66]
我就想说一句 如果各大论坛和媒体交流平台都刷满表情包会不会很有意思、
各种可行性我懒得分析、但法律上我觉得不违法

**Comment by CPdogson** [comment]
有这类活动了啊

https://996tsc.github.io/#/sticker

有些时候会侵犯马云之流的肖像权之类的，但个人的话应该不会收到律师函，放心干吧

**Comment by chensuoxin** [comment]
效果上、好像以前大陆刷过台湾的、还是挺受欢迎的、这件事在王尼玛的那个视频中有提过、但之前是在贴吧聚集的

**Comment by chensuoxin** [comment]
> 
> 
> 有这类活动了啊
> 
> https://996tsc.github.io/#/sticker
> 
> 有些时候会侵犯马云之流的肖像权之类的，但个人的话应该不会收到律师函，放心干吧

问题在于没有集体行动、没有一次好玩的

**Comment by CPdogson** [comment]
> 
> 
> > 有这类活动了啊
> > https://996tsc.github.io/#/sticker
> > 有些时候会侵犯马云之流的肖像权之类的，但个人的话应该不会收到律师函，放心干吧
> 
> 问题在于没有集体行动、没有一次好玩的

集体策划可能就真要考虑肖像权、图片版权这类的问题了，最好是个体自发行动
我可以想想如何处理这些问题，不过这也是一个不错的活动
你也可以尝试策划一个
