### ISSUE TITLE
#向马云寄劳动法# 建议寄书行为借鉴电商模式，在马云的淘宝开店，提供购书并邮寄服务

### ISSUE THREAD

**Issue by Ron233** [CPdogson/996action#68]

**Comment by CPdogson** [comment]
我理解能力不是很好

是淘宝上开一家店，只要给这家店付钱，这家店帮助寄劳动法的意思吗？

可是这里面的成本/利润由谁负担？

**Comment by Ron233** [comment]
> 我理解能力不是很好
> 
> 是淘宝上开一家店，只要给这家店付钱，这家店帮助寄劳动法的意思吗？
> 
> 可是这里面的成本/利润由谁负担？

为啥要盈利不就是五四这次而已嘛？淘宝店注册现在又不用什么钱
