### ISSUE TITLE
直观的显示有多少人在加班－－还在加班？来点亮地图

### ISSUE THREAD

**Issue by xiallyspider** [CPdogson/996action#71]
**是否可以制作一个可视化的地图网站？**
1. 除开正常上班（不要说９９６是正常上班时间），进入加班时间，点亮地图上你的位置，下班走人就关闭（获取当前用户位置、在地图上绘制一个高亮点）
2. 区分工种，记录人数、加班时长
3. 因加班长时间未休息导致身体出现问题（晕倒、cu si等），发出红色警报【需要审核】
4. 面向所有工种（不同工种的正常上班时间不同。要注意区分，保持客观）
5. 在５.1前能做好最好，作为证据展示

个人能力有限，希望大家可以一起来完善

**Comment by CPdogson** [comment]
这是一个非常不错的想法，我见过类似的案例。
可是我是做后端的，对前端不怎么熟悉，slack里我知道有一位做前端的在做GitHub的社区以聚合方式呈现，你的想法可以在群内来找合作伙伴。

**Comment by xiallyspider** [comment]
好的，我去看看

**Comment by OpenMarshall** [comment]
@xiallyspider @CPdogson 我做了一个类似的 https://itunes.apple.com/cn/app/id1460125845

**Comment by CPdogson** [comment]
已有成品，转至以下链接讨论
https://github.com/CPdogson/996action/issues/92
