### ISSUE TITLE
关于#向马云寄劳动法#活动的几点建议

### ISSUE THREAD

**Issue by rain512** [CPdogson/996action#73]
1.请实施活动的小伙伴们，一定，一定要注意安全。
    大家都是程序员，线上个人情报注意保护，线下注意不法分子的利用。
2.希望海外程序员也加入进来。

今天的我们要发扬五四精神
前事不忘後事之師

**Comment by CPdogson** [comment]
感谢您的建议

另外我把一些话删除了，这些话只会成为我们行动的阻碍

action版面是需要记者采访的

海外程序员已经加入进来了，在icu主re有一个签名页面

**Comment by rain512** [comment]
写完后，也觉得有句话不妥，提交后没法修改。
感谢你的修正
