### ISSUE TITLE
Students' lives matter.

### ISSUE THREAD

**Issue by zaoqi** [CPdogson/996action#74]

**Comment by CPdogson** [comment]
I think so,but what should we do?

**Comment by zaoqi** [comment]
@CPdogson 什麼都做不了，除了選擇離開此(某些人說是`7-10-7`)，去境外。

**Comment by CPdogson** [comment]
I think you understand what we are doing, don't be discouraged.

we need more encouragement ，so I well close it.

**Comment by zaoqi** [comment]
So people don't need reality, they just need positive things.

註：開發者可以做某些事情來改變他們的情況

**Comment by CPdogson** [comment]
Not yet, people change the world through action.
So 996action was born,Everyone can join us.
