### ISSUE TITLE
#向马云寄劳动法#有个疑问，不会被拒收吗？

### ISSUE THREAD

**Issue by iamhankai** [CPdogson/996action#82]
你寄过去，人家直接拒收不就完事了？

**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by CPdogson** [comment]
https://github.com/CPdogson/996action/blob/master/black-and-white.md#qa

请阅读完全文后进行提问，我支持任何第三方平台的发展，故本issues会保留一段时间
