### ISSUE TITLE
996行动

### ISSUE THREAD

**Issue by bulusite** [CPdogson/996action#84]
我们参加了一个几乎没有胜算的游戏
只要邪恶还没有收到惩罚
就总会有人去挑战那不合理的制度
那些相信真理追随理想的人
那些会一直战斗到底的人

**Comment by CPdogson** [comment]
朋友，行动起来吧，积跬步聚小流的过程中看不到千里和江河很正常，可是三五年后呢？谁也说不准

**Comment by ping-jz** [comment]
慢慢动起来吧

**Comment by CPdogson** [comment]
> 
> 
> 慢慢动起来吧

我把标题改成996行动吧，没必要用这么刺眼的词来描述我们目前的状态
