### ISSUE TITLE
关于封禁GitHub的可能性分析

### ISSUE THREAD

**Issue by YouthMarxist** [CPdogson/996action#85]
你又不是没有体验过被疯的事情，这种担心不是没有理由的。

**Comment by CPdogson** [comment]
您要相信我们政府是站在劳动者这边的，我们采取的全都是经过合法性分析的行动。

**Comment by hhm1999** [comment]
封掉又如何，有多少有名的站点被封了，谷歌被封不是照样访问

**Comment by YouthMarxist** [comment]
各位又不是没有领教过国家的强制力，你看看上次触及了底线，国家机器开动后的后果。
我一直觉得“工作时长”问题往广泛意义上说，几乎肯定会和“向左走向右走”相关联。
国家高速奔跑的列车由起最活跃的市场经济来刺激拉动，没有“工作时长”根本不可能一次又一次的10%增长率啊。

总之，大家还是留点心：**别到时候把锅给你凿漏，锅台给你扒了，烧火的厨子给你赶到猪圈去喂猪**。

**Comment by CPdogson** [comment]
> 各位又不是没有领教过国家的强制力，你看看上次触及了底线，国家机器开动后的后果。
> 我一直觉得“工作时长”问题往广泛意义上说，几乎肯定会和“向左走向右走”相关联。
> 国家高速奔跑的列车由起最活跃的市场经济来刺激拉动，没有“工作时长”根本不可能一次又一次的10%增长率啊。
> 
> 总之，大家还是留点心：**别到时候把锅给你凿漏，锅台给你扒了，烧火的厨子给你赶到猪圈去喂猪**。

我再次强调我们的行动全部合法，和你举得例子不同，这里没有言论管制你大可直接说，但我因为保证issues可以接受国内媒体查阅，会将它删除。暴力机器一次次砸在人民头上，失望的是不仅仅是一些个人，而是十三亿劳动者。

**Comment by YouthMarxist** [comment]
可能此issue没有意义。
我认为996action说到底是一种斗争，不管是以什么方式来进行。这种借助open-source媒介为了大范围扭转社会阶层运行机制的事情，可行吗？可控吗？可实施？最后谁来认可？
还是希望996action能够有个好的开始，取得好的结果。


同意@CPdogson删除该issue。
