### ISSUE TITLE
关于发动国产自写开源项目禁止996公司使用的建议

### ISSUE THREAD

**Issue by Aetco** [CPdogson/996action#86]
禁止用作996公司生产工具

**Comment by CPdogson** [comment]
https://github.com/kattgu7/Anti-996-License

你指的是这个协议吗？可以去他们的GitHub上讨论，和帮助他们，我们是分工关系。
关于协议的制定和完善由Anti-996-License负责，案例的制造和倡导活动可能会放到996.law和996action上，具体怎么操作我也需要和他们商量。
