### ISSUE TITLE
54活动怎么样了——寄送劳动法反馈贴

### ISSUE THREAD

**Issue by 94kai** [CPdogson/996action#89]
54活动怎么样

**Comment by CPdogson** [comment]
https://github.com/CPdogson/996action/blob/master/54law/pic.md

图片我整理了一些，微博在不主动搜索的情况下#五四向马云寄劳动法#已经有31.2万阅读726讨论（截至12点），短视频那边似乎是全线屏蔽。

现在微博几乎话题一有热度就开始屏蔽，累计阅读估计过千万，这件事情可以说非常成功了。

**Comment by 94kai** [comment]
👍

**Comment by ping-jz** [comment]
加油

**Comment by ShuaiShuaiLee** [comment]
往头条再发一波图片！头条环境比微博好多了！条友说话一个比一个好听！
