### ISSUE TITLE
做了个加班地图 App，一眼看到你附近哪里有人在加班

### ISSUE THREAD

**Issue by OpenMarshall** [CPdogson/996action#92]
可以看到你附近有谁在 996 上下班，还能一键找 TA 私聊
戳链接：https://itunes.apple.com/cn/app/id1460125845

**Comment by CPdogson** [comment]
干得漂亮，为什么不在slack中分享，有HTML版本和安卓版吗

**Comment by OpenMarshall** [comment]
@CPdogson 求个 slack 邀请，x_os@outlook.com

**Comment by CPdogson** [comment]
slack邀请就在996.icu的主页上，action的主页上也有啊
https://join.slack.com/t/996icu/shared_invite/enQtNjI0MjEzMTUxNDI0LTkyMGViNmJiZjYwOWVlNzQ3NmQ4NTQyMDRiZTNmOWFkMzYxZWNmZGI0NDA4MWIwOGVhOThhMzc3NGQyMDBhZDc

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
