### ISSUE TITLE
中国政府从不主动解决问题，它只会主动解决提出问题的人。为了引起最高层的重视，我们可能需要「郭文贵爆料革命 · 启蒙开智入门指南」

### ISSUE THREAD

**Issue by Pangu2020together** [CPdogson/996action#95]
https://github.com/ourhimalayas/txt/issues/1

**Comment by CPdogson** [comment]
996action的issues还有国内的记者访问，请不要让他变成一个被拒绝报道的地方，谢谢

我们注重的是行动

Sent from ProtonMail Mobile

开启 周三, 5月 8, 2019 在 10:15, 2020 相聚盘古龙头 <notifications@github.com> 写道：

**Comment by Pangu2020together** [comment]
目前都是党的喉舌，小骂大帮忙，形同鸡肋。
有良知的记者，脊梁骨都被打断了，膝盖也都跪坏了。
他们都自顾不暇、自身难保的情况下，你还指望着他们能帮？
最高法也明确表明司法不独立，因此通过法律维权一点意义都没有。

截止到目前，我还真没见到 996ICU 行动有什么实质性的成果。
党的喉舌们稍微出来说几句所谓的公道话，大家就感恩戴德了？
外媒报道了，Python 之父及微软部分员工也声援了，但请问究竟有什么变化吗？
显然没有，也绝对不可能有，因为老共根本就不在乎这些不痛不痒的请愿与申诉。

老共从来不会主动解决问题，它只会解决提出问题的人，这已经是常识。
否则你也不必申请匿名账号来创建这些完全合法合理的项目，以保护自身安全。
即便是体制内有良知的人，现阶段也不可能从实质上帮到我们，因为他们人人自危。
我们唯一能做的，就是通过爆料革命，联合体制内的有识之士，里应外合，推翻这个腐朽的体制。
也只有这样才能带来新闻言论自由，司法公正独立，我们的维权才会更有意义，或根本就不需要维权！

**Comment by rain512** [comment]
这是反动的，请马上删除，不要给我们程序员抹黑。

**Comment by Pangu2020together** [comment]
@rain512 抱歉，我们才是真正的程序员，你才是在给我们抹黑。

**Comment by CPdogson** [comment]
有良知的人记者很多，至少我遇到了很多，还有国外的记者

因为部分人否定全部人，这种范围人身攻击是我是不认可的，我再次强调，我们的行动都应该在合法范围内，请不要捣乱

Sent from ProtonMail Mobile

开启 周三, 5月 8, 2019 在 14:59, 2020 相聚盘古龙头 <notifications@github.com> 写道：

**Comment by cerebrowang** [comment]
不要扯上郭XX
