### ISSUE TITLE
对于马云的最新言论，希望各位能放下争执与偏见，争取合作与共识

### ISSUE THREAD

**Issue by CPdogson** [CPdogson/996action#96]
大致以马云和669为关键词搜索就可以了

https://pbs.twimg.com/media/D6MUMwvUEAAarLd.jpg

无论之前各位对女权如何看待，希望在这件事情上统一对外，我个人表态将尊重女性的自由选择和劳动权，也将尊重残障等少数群体的自由选择和劳动权！

IT行业中有女性，劳动者中更不乏女性，对待这件事情希望各位能放下过去的不愉快（如果有的话），合作前行。

**Comment by ping-jz** [comment]
网页访问不了

**Comment by huanghe2015** [comment]
文章已被删除

**Comment by CPdogson** [comment]
https://pbs.twimg.com/media/D6MUMwvUEAAarLd.jpg
